ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "profiles" FORCE ROW LEVEL SECURITY;
CREATE POLICY "profiles_isolate_owner" ON "profiles"
  USING ("user_id" = current_setting('app.current_user_id', true))
  WITH CHECK ("user_id" = current_setting('app.current_user_id', true));

ALTER TABLE "tasks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tasks" FORCE ROW LEVEL SECURITY;
CREATE POLICY "tasks_isolate_owner" ON "tasks" USING ("user_id" = current_setting('app.current_user_id', true)) WITH CHECK ("user_id" = current_setting('app.current_user_id', true));
ALTER TABLE "habits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "habits" FORCE ROW LEVEL SECURITY;
CREATE POLICY "habits_isolate_owner" ON "habits" USING ("user_id" = current_setting('app.current_user_id', true)) WITH CHECK ("user_id" = current_setting('app.current_user_id', true));
ALTER TABLE "habit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "habit_logs" FORCE ROW LEVEL SECURITY;
CREATE POLICY "habit_logs_isolate_owner" ON "habit_logs" USING ("user_id" = current_setting('app.current_user_id', true)) WITH CHECK ("user_id" = current_setting('app.current_user_id', true));
ALTER TABLE "finance_transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "finance_transactions" FORCE ROW LEVEL SECURITY;
CREATE POLICY "finance_transactions_isolate_owner" ON "finance_transactions" USING ("user_id" = current_setting('app.current_user_id', true)) WITH CHECK ("user_id" = current_setting('app.current_user_id', true));
ALTER TABLE "water_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "water_logs" FORCE ROW LEVEL SECURITY;
CREATE POLICY "water_logs_isolate_owner" ON "water_logs" USING ("user_id" = current_setting('app.current_user_id', true)) WITH CHECK ("user_id" = current_setting('app.current_user_id', true));
ALTER TABLE "meals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "meals" FORCE ROW LEVEL SECURITY;
CREATE POLICY "meals_isolate_owner" ON "meals" USING ("user_id" = current_setting('app.current_user_id', true)) WITH CHECK ("user_id" = current_setting('app.current_user_id', true));
ALTER TABLE "groceries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "groceries" FORCE ROW LEVEL SECURITY;
CREATE POLICY "groceries_isolate_owner" ON "groceries" USING ("user_id" = current_setting('app.current_user_id', true)) WITH CHECK ("user_id" = current_setting('app.current_user_id', true));
ALTER TABLE "calendar_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "calendar_events" FORCE ROW LEVEL SECURITY;
CREATE POLICY "calendar_events_isolate_owner" ON "calendar_events" USING ("user_id" = current_setting('app.current_user_id', true)) WITH CHECK ("user_id" = current_setting('app.current_user_id', true));
ALTER TABLE "goals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "goals" FORCE ROW LEVEL SECURITY;
CREATE POLICY "goals_isolate_owner" ON "goals" USING ("user_id" = current_setting('app.current_user_id', true)) WITH CHECK ("user_id" = current_setting('app.current_user_id', true));
ALTER TABLE "semesters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "semesters" FORCE ROW LEVEL SECURITY;
CREATE POLICY "semesters_isolate_owner" ON "semesters" USING ("user_id" = current_setting('app.current_user_id', true)) WITH CHECK ("user_id" = current_setting('app.current_user_id', true));
ALTER TABLE "courses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "courses" FORCE ROW LEVEL SECURITY;
CREATE POLICY "courses_isolate_owner" ON "courses" USING ("user_id" = current_setting('app.current_user_id', true)) WITH CHECK ("user_id" = current_setting('app.current_user_id', true));
ALTER TABLE "ai_actions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_actions" FORCE ROW LEVEL SECURITY;
CREATE POLICY "ai_actions_isolate_owner" ON "ai_actions" USING ("user_id" = current_setting('app.current_user_id', true)) WITH CHECK ("user_id" = current_setting('app.current_user_id', true));
