import React,{useMemo,useState} from "react";
import {ArrowRight,CalendarClock,CheckCircle2,Clock3,Droplets,Moon,Play,RefreshCw,Sun,Target} from "lucide-react";
import {dayPlan,nextAction} from "./smartPlanner";

const dot={high:"bg-[#b44f57]",medium:"bg-[#d6a33d]",low:"bg-[#67916f]"};
const label={high:"High",medium:"Medium",low:"Low"};

export default function SmartPlanner({data,Card,SectionTitle,toggleTask}){
  const [mode,setMode]=useState("today"),[recommendation,setRecommendation]=useState(null);
  const base=useMemo(()=>{const d=new Date();if(mode==="tomorrow")d.setDate(d.getDate()+1);return d},[mode]);
  const plan=useMemo(()=>dayPlan(data,base),[data,base]);
  const review=mode==="review";
  const dateLabel=new Intl.DateTimeFormat("mn-MN",{weekday:"long",year:"numeric",month:"long",day:"numeric"}).format(base);
  const score=Math.round((plan.completion+(plan.goals.length?Math.min(100,(data.goals.filter(g=>g.done).length/data.goals.length)*100):100))/2);
  return <div className="smart-plan space-y-5">
    <div className="smart-hero rounded-[28px] bg-[#7b3f55] p-6 text-white shadow-xl md:p-8">
      <div className="relative z-10 max-w-2xl"><div className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-[#e9cfd8]">Smart Daily Planner</div><h1 className="serif text-3xl font-bold md:text-4xl">Өдрөө санаатайгаар бүтээ.</h1><p className="mt-2 text-sm text-[#f4e7eb]">{dateLabel} · Таны planner-ийн мэдээллээс offline боловсруулав.</p></div>
      <div className="relative z-10 mt-5 flex flex-wrap gap-2"><button className="btn bg-white text-[#713a50]" onClick={()=>setMode("today")}><Sun size={17} className="mr-2 inline"/>Plan my day</button><button className="btn bg-white/12 text-white" onClick={()=>setMode("review")}><Moon size={17} className="mr-2 inline"/>Review my day</button><button className="btn bg-white/12 text-white" onClick={()=>setMode("tomorrow")}><CalendarClock size={17} className="mr-2 inline"/>Plan tomorrow</button></div>
    </div>
    <button className="next-action-card w-full rounded-[24px] border border-[#dec8cf] bg-[#fffaf9] p-5 text-left shadow-sm" onClick={()=>setRecommendation(nextAction(data))}>
      <div className="flex items-center justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.16em] text-[#a16f81]">Right now</div><h2 className="mt-1 text-xl font-black text-[#563642]">What should I do now?</h2>{recommendation&&<div className="mt-3"><div className="font-bold text-[#7b3f55]">{recommendation.title}</div><p className="mt-1 text-sm text-[#8d6d78]">{recommendation.reason}</p></div>}</div><span className="rounded-full bg-[#7b3f55] p-3 text-white">{recommendation?<RefreshCw size={20}/>:<ArrowRight size={20}/>}</span></div>
    </button>
    {review?<Review plan={plan} score={score}/>:<>
      <div className="grid gap-4 md:grid-cols-3"><Metric name="Day completion" value={`${plan.completion}%`} pct={plan.completion}/><Metric name="Habits" value={`${plan.habitDone}/${plan.habits.length}`} pct={plan.habits.length?plan.habitDone/plan.habits.length*100:0}/><Metric name="Water" value={`${plan.water}/8`} pct={plan.water/8*100}/></div>
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(320px,.8fr)]">
        <Card><SectionTitle icon={Clock3} title={mode==="tomorrow"?"Tomorrow's timeline":"Today's timeline"} sub="Tasks, events, and wellness anchors"/>{plan.timeline.length?<div className="relative space-y-1 before:absolute before:bottom-4 before:left-[54px] before:top-4 before:w-px before:bg-[#eadde1]">{plan.timeline.map(x=><div key={x.id} className="relative grid grid-cols-[44px_12px_1fr] items-start gap-2 py-2"><span className="pt-2 text-xs font-black text-[#7b3f55]">{x.time}</span><span className={`z-10 mt-3 h-2.5 w-2.5 rounded-full ${x.kind==="event"?"bg-[#7b3f55]":x.kind==="wellness"?"bg-[#c68b9d]":dot[x.priority]}`}/><div className={`rounded-2xl p-3 ${x.kind==="wellness"?"border border-[#ead7de] bg-[#fff8f7]":"bg-[#fbf7f7]"}`}><div className="font-bold">{x.title}</div><div className="mt-1 text-xs text-[#9b7d87]">{x.kind==="event"?"Calendar event":x.kind==="wellness"?`Wellness · ${x.duration} min`:`${x.duration} min · ${label[x.priority]} priority`}</div></div></div>)}</div>:<EmptyPlan/>}</Card>
        <div className="space-y-5"><Card><SectionTitle icon={Target} title="Top priorities" sub="Due date, importance, events, goals"/><div className="space-y-2">{plan.open.slice(0,5).map(t=><label key={t.id} className="flex cursor-pointer items-center gap-3 rounded-2xl bg-[#fbf7f7] p-3"><input type="checkbox" className="check" checked={t.done} onChange={()=>toggleTask(t.id)}/><span className={`h-2.5 w-2.5 rounded-full ${dot[t.smartPriority.level]}`}/><span className="min-w-0 flex-1 text-sm font-bold">{t.text}</span><span className="text-[10px] font-black uppercase text-[#9b7d87]">{label[t.smartPriority.level]}</span></label>)}{plan.done.map(t=><label key={t.id} className="flex cursor-pointer items-center gap-3 rounded-2xl bg-[#fbf7f7] p-3"><input type="checkbox" className="check" checked onChange={()=>toggleTask(t.id)}/><span className="min-w-0 flex-1 text-sm font-bold text-[#a88e97] line-through">{t.text}</span><span className="text-[10px] font-black uppercase text-[#9b7d87]">Done</span></label>)}{!plan.tasks.length&&<EmptyPlan text="Энэ өдөрт task алга байна."/>}</div></Card><Card><SectionTitle icon={CheckCircle2} title="Daily anchors"/><div className="space-y-3 text-sm"><Row name="Calendar events" value={plan.events.length}/><Row name="Habits remaining" value={plan.habits.length-plan.habitDone}/><Row name="Meals planned" value={Object.values(data.meals?.[plan.day]||{}).filter(Boolean).length}/><Row name="Important goals" value={plan.goals.length}/><Row name="Water remaining" value={`${Math.max(0,8-plan.water)} cups`}/></div>{plan.goals.length>0&&<div className="mt-3 space-y-2">{plan.goals.slice(0,3).map(goal=><div key={goal.id} className="rounded-xl bg-[#fbf7f7] px-3 py-2 text-sm font-bold">{goal.text}</div>)}</div>}</Card></div>
      </div>
    </>}
  </div>
}
function Metric({name,value,pct}){return <div className="card p-4"><div className="flex items-end justify-between"><span className="text-sm font-bold text-[#93717d]">{name}</span><b className="text-2xl text-[#633848]">{value}</b></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#f0e2e7]"><div className="h-full rounded-full bg-[#7b3f55] transition-all" style={{width:`${Math.min(100,pct)}%`}}/></div></div>}
function Row({name,value}){return <div className="flex justify-between rounded-xl bg-[#fbf7f7] px-3 py-2"><span className="text-[#896b76]">{name}</span><b>{value}</b></div>}
function EmptyPlan({text="Энэ өдөрт төлөвлөсөн зүйл алга."}){return <div className="rounded-2xl bg-[#faf5f6] p-5 text-center text-sm text-[#9b7d87]">{text}</div>}
function Review({plan,score}){const suggestion=plan.open.length?`Маргааш “${plan.open[0].text}” ажлыг өдрийн эхний төвлөрөх блокт оруулаарай.`:plan.water<8?"Маргааш ус уух сануулгаа өглөө бэлдээрэй.":"Өнөөдрийн хэмнэлээ хадгалж, маргаашийн нэг гол зорилгоо сонгоорой.";return <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Card><SectionTitle icon={Moon} title="Overall daily score" sub="Tasks, habits, water, goals"/><div className="flex items-center gap-5"><div className="flex h-28 w-28 items-center justify-center rounded-full border-[10px] border-[#ead7de] text-3xl font-black text-[#7b3f55]">{score}</div><div><b className="text-lg">{score>=80?"Strong finish":score>=50?"Good progress":"Fresh start"}</b><p className="mt-1 text-sm text-[#93717d]">Өдөр бүрийн жижиг ахиц нийлж том үр дүн болно.</p></div></div></Card><Card><SectionTitle icon={CheckCircle2} title="Evening review"/><div className="grid gap-2 sm:grid-cols-2"><Row name="Tasks completed" value={plan.done.length}/><Row name="Tasks unfinished" value={plan.open.length}/><Row name="Habit completion" value={`${plan.habitDone}/${plan.habits.length}`}/><Row name="Water progress" value={`${plan.water}/8`}/><Row name="Goal progress" value={`${plan.goals.length} active`}/></div><div className="mt-4 rounded-2xl bg-[#f5e8ed] p-4 text-sm"><b className="text-[#713a50]">Tomorrow's improvement</b><p className="mt-1 text-[#795965]">{suggestion}</p></div></Card></div>}
